#!/usr/bin/env python
"""Every ordinary file on Meera's laptop is evidence the participant can
cite -- not only the ten affair photos. This stamps an evidence_id into each
node of desktop-shell's dir.json, appends the matching evidence_cache rows to
db/init.sql (fresh installs), and prints the same INSERT to apply to a live
database (so a running game keeps its discoveries):

    python scripts/seed_laptop_files.py | docker compose exec -T mercy-engine-db psql -U mercy -d mercy_engine
"""
import io
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
DIR_JSON = os.path.join(HERE, '..', '..', 'desktop-shell', 'src', 'reducers', 'dir.json')
INIT_SQL = os.path.join(HERE, '..', 'db', 'init.sql')
LAPTOP = 'http://localhost:3000'
MARK = '-- laptop-files (generated by scripts/seed_laptop_files.py)'

# path in dir.json -> record. Timestamps are the filename dates; summaries are
# what the picker searches, captions are what the evidence card shows.
FILES = [
    ('Users/Meera/Pictures/Camera Roll/IMG_20181007_073012.jpg', 'LAP-PHOTO-11', 'photo', '2018-10-07 07:30:00+05:30',
     'Breakfast with Dad at the Malleshwaram house, 7 October 2018 -- a week before he died. Dosas, the newspaper, his tea.',
     ['meera', 'ravi_sharma'], {'caption': 'Dad at breakfast, Malleshwaram, 7 October 2018. The last photo of him on this laptop.'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20240316_190455.jpg', 'LAP-PHOTO-12', 'photo', '2024-03-16 19:04:00+05:30',
     'College final-year project night, re-saved 16 March 2024: Nikhil, Rahul, Meera and Priya around one laptop.',
     ['meera', 'rahul', 'nikhil', 'priya'], {'caption': 'Final-year project night, college. Nikhil, Rahul standing, Meera, Priya.'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20240505_101233.jpg', 'LAP-PHOTO-13', 'photo', '2024-05-05 10:12:00+05:30',
     'Meera and Bruno in the garden, 5 May 2024.',
     ['meera'], {'caption': 'Meera and Bruno in the garden, 5 May 2024.'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20240505_101410.jpg', 'LAP-PHOTO-14', 'photo', '2024-05-05 10:14:00+05:30',
     "Bruno's fourth birthday, 5 May 2024 -- balloons, a chicken cake, the banner.",
     ['meera'], {'caption': "Bruno's fourth birthday, 5 May 2024. The chicken cake did not survive the afternoon."}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20240622_123301.jpg', 'LAP-PHOTO-15', 'photo', '2024-06-22 12:33:00+05:30',
     'Sunday brunch at the cafe, 22 June 2024. Alone at the table; avocado toast and a flat white.',
     ['meera'], {'caption': 'Sunday brunch, 22 June 2024. Alone at the table.'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20240817_203344.jpg', 'LAP-PHOTO-16', 'photo', '2024-08-17 20:33:00+05:30',
     "Dinner with Arjun, 17 August 2024 -- Dad's birthday. Candles; the chalkboard reads 'same people, brighter nights'.",
     ['meera', 'arjun'], {'caption': "Dinner with Arjun on Dad's birthday, 17 August 2024."}),
    # --- the wedding, 14 February 2021 (Pictures/Wedding) -----------------------------------
    ('Users/Meera/Pictures/Wedding/IMG_20210214_091204.jpg', 'LAP-PHOTO-17', 'photo', '2021-02-14 09:12:00+05:30',
     'Their wedding, 14 February 2021: Meera and Arjun seated at the ceremony, her head on his shoulder, the lamps lit in front of them.',
     ['meera', 'arjun'], {'caption': 'The ceremony, 14 February 2021.'}),
    ('Users/Meera/Pictures/Wedding/IMG_20210214_094811.jpg', 'LAP-PHOTO-18', 'photo', '2021-02-14 09:48:00+05:30',
     'Their wedding, 14 February 2021: Arjun tying the thaali, her head bowed, elders behind them.',
     ['meera', 'arjun'], {'caption': 'The thaali, 14 February 2021.'}),
    ('Users/Meera/Pictures/Wedding/IMG_20210214_100539.jpg', 'LAP-PHOTO-19', 'photo', '2021-02-14 10:05:00+05:30',
     'Their wedding, 14 February 2021: the two of them walking away from the mandap, seen from behind, her plait to her waist.',
     ['meera', 'arjun'], {'caption': 'Walking away from the mandap, 14 February 2021.'}),
    ('Users/Meera/Pictures/Wedding/IMG_20210214_103217.jpg', 'LAP-PHOTO-20', 'photo', '2021-02-14 10:32:00+05:30',
     'Their wedding, 14 February 2021: Meera laughing behind her hand at something Arjun has said.',
     ['meera', 'arjun'], {'caption': 'Laughing at something he said, 14 February 2021.'}),
    ('Users/Meera/Pictures/Wedding/IMG_20210214_104755.jpg', 'LAP-PHOTO-21', 'photo', '2021-02-14 10:47:00+05:30',
     'Their wedding, 14 February 2021: garlanded, rice being thrown over them by the guests.',
     ['meera', 'arjun'], {'caption': 'Garlanded, 14 February 2021.'}),
    ('Users/Meera/Pictures/Wedding/IMG_20210214_112033.jpg', 'LAP-PHOTO-22', 'photo', '2021-02-14 11:20:00+05:30',
     'Their wedding, 14 February 2021: signing the register together -- the same register entry the certificate in Documents is taken from.',
     ['meera', 'arjun'], {'caption': 'Signing the register, 14 February 2021.'}),
    # --- the two of them, married life (Pictures/Camera Roll) --------------------------------
    ('Users/Meera/Pictures/Camera Roll/IMG_20221224_154512.jpg', 'LAP-PHOTO-23', 'photo', '2022-12-24 15:45:00+05:30',
     'On a train with Arjun, 24 December 2022, bags at their feet -- the start of a Christmas trip.',
     ['meera', 'arjun'], {'caption': 'On the train, 24 December 2022.'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20221224_161830.jpg', 'LAP-PHOTO-24', 'photo', '2022-12-24 16:18:00+05:30',
     'The same train journey, 24 December 2022: Meera at the window, Arjun looking at her.',
     ['meera', 'arjun'], {'caption': 'At the window, 24 December 2022.'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20221225_083447.jpg', 'LAP-PHOTO-25', 'photo', '2022-12-25 08:34:00+05:30',
     'A viewpoint over the hills and the lake, 25 December 2022: the two of them at the railing, his backpack on.',
     ['meera', 'arjun'], {'caption': 'The viewpoint, 25 December 2022.'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20231112_183002.jpg', 'LAP-PHOTO-26', 'photo', '2023-11-12 18:30:00+05:30',
     'Diwali at the flat, 12 November 2023: Arjun on a stool hanging the marigold garlands, Meera passing them up.',
     ['meera', 'arjun'], {'caption': 'Diwali at the flat, 12 November 2023.'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20240204_133928.jpg', 'LAP-PHOTO-27', 'photo', '2024-02-04 13:39:00+05:30',
     'Cooking together in their kitchen, 4 February 2024; he is stealing a taste out of the pan.',
     ['meera', 'arjun'], {'caption': 'Sunday lunch, 4 February 2024.'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20240312_210715.jpg', 'LAP-PHOTO-28', 'photo', '2024-03-12 21:07:00+05:30',
     "Meera's twenty-sixth birthday at home, 12 March 2024: the banner, the candles, the cake with her name on it, Arjun beside her.",
     ['meera', 'arjun'], {'caption': 'Her birthday, 12 March 2024. Ten days before the diary entry that starts with "I did something stupid".'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20240519_222104.jpg', 'LAP-PHOTO-29', 'photo', '2024-05-19 22:21:00+05:30',
     'A Sunday night on the sofa, 19 May 2024: Arjun asleep under the blanket with the television on, Meera laughing at him.',
     ['meera', 'arjun'], {'caption': 'Sunday night, 19 May 2024.'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20240608_112640.jpg', 'LAP-PHOTO-30', 'photo', '2024-06-08 11:26:00+05:30',
     'A selfie of the two of them at home, 8 June 2024 -- two weeks before the first mail from N.',
     ['meera', 'arjun'], {'caption': 'At home, 8 June 2024.'}),
    # --- screenshots off her phone (Pictures/Screenshots) ------------------------------------
    ('Users/Meera/Pictures/Screenshots/Screenshot_20260914_221408.png', 'LAP-PHOTO-31', 'photo', '2026-09-14 22:14:00+05:30',
     'Screenshot of a Vayo ride receipt: Srinivasa Residency, Koramangala to Phoenix Marketcity, 21:12 to 21:47, Rs 486 paid by UPI, booking VY02609141237.',
     ['meera'], {'caption': 'Vayo ride receipt, Koramangala to Phoenix Marketcity.'}),
    ('Users/Meera/Pictures/Screenshots/Screenshot_20260915_164102.png', 'LAP-PHOTO-32', 'photo', '2026-09-15 16:41:00+05:30',
     "Screenshot of a Shopara order, delivered: a brown leather laptop bag, Rs 3,299, marked as a gift for Arjun -- \"For all your big plans and bigger dreams\".",
     ['meera', 'arjun'], {'caption': 'A gift ordered for Arjun, delivered 15 September.'}),
    ('Users/Meera/Pictures/Screenshots/Screenshot_20260921_211432.png', 'LAP-PHOTO-33', 'photo', '2026-09-21 21:14:00+05:30',
     'Screenshot of a UPI payment: Rs 2,450 to The Spice Room, Bengaluru, 20:42, note "Dinner with Arjun".',
     ['meera', 'arjun'], {'caption': 'Dinner with Arjun, paid at 20:42 the evening before last.'}),
    ('Users/Meera/Pictures/Screenshots/Screenshot_20260922_102843.png', 'LAP-PHOTO-34', 'photo', '2026-09-22 10:28:00+05:30',
     'Screenshot of a hotel booking: The Lakeside Retreat, Ooty, two adults, Arjun Kapoor and Meera Kapoor, Rs 12,480, reference HTL7264913.',
     ['meera', 'arjun'], {'caption': 'A booking for the two of them at Ooty.'}),
    ('Users/Meera/Pictures/Screenshots/Screenshot_20260922_182715.png', 'LAP-PHOTO-35', 'photo', '2026-09-22 18:27:00+05:30',
     'Screenshot of a restaurant reservation: The Olive & Oak, Lavelle Road, Saturday 19:30, two guests, Meera Kapoor and Arjun Kapoor, window seat requested.',
     ['meera', 'arjun'], {'caption': 'A table booked for Saturday -- made hours before she disappeared.'}),
    ('Users/Meera/Desktop/todo.txt', 'LAP-DOC-01', 'document', '2024-08-28 09:00:00+05:30',
     'todo.txt on the desktop: water bill, call Priya re Sunday, Bruno vet Saturday, return the dish, ask Arjun about Coorg dates, cancel the gym before the 30th.',
     ['meera'], {'caption': 'todo.txt, on the desktop.', 'body': None}),
    ('Users/Meera/Documents/notes.txt', 'LAP-DOC-02', 'document', '2024-08-20 21:00:00+05:30',
     "notes.txt in Documents: recipes to try (bisi bele bath, Dad's proportions from the diary), books, and a birthday gift idea for Arjun.",
     ['meera'], {'caption': 'notes.txt, in Documents.', 'body': None}),
    ('Users/Meera/Documents/Insurance/LIC_policy_2019.pdf', 'LAP-DOC-03', 'document', '2019-03-19 00:00:00+05:30',
     'LIC Jeevan Anand policy schedule, commenced 19 March 2019: life assured Meera Sharma, born 12 March 1998, sum assured Rs 10 lakh, nominee Lakshmi Sharma (mother).',
     ['meera'], {'caption': 'LIC policy schedule, 2019. Nominee: her mother.', 'url': LAPTOP + '/files/docs/LIC_policy_2019.pdf'}),
    ('Users/Meera/Documents/Office/Q2_review_notes.txt', 'LAP-DOC-04', 'document', '2024-07-08 18:30:00+05:30',
     'Q2 review talking points from work: accounts, renewals, the onboarding flow.',
     ['meera'], {'caption': 'Q2_review_notes.txt, in Documents/Office.', 'body': None}),
    ('Users/Meera/Downloads/PulseFit-export-Aug.csv', 'LAP-DOC-05', 'document', '2024-08-31 00:00:00+05:30',
     "PulseFit export for August 2024: daily steps, resting heart rate and sleep hours from Meera's band.",
     ['meera'], {'caption': 'PulseFit-export-Aug.csv, in Downloads.', 'body': None}),
    ('Users/Meera/Downloads/Coorg homestay - Wanderly.pdf', 'LAP-DOC-06', 'document', '2024-08-12 00:00:00+05:30',
     'Wanderly booking confirmation WDL-8H3K2Q: Misty Ridge Homestay, Madikeri, Coorg, 30 August to 1 September 2024, 2 adults, pet-friendly. Free cancellation until 23 August.',
     ['meera', 'arjun'], {'caption': 'Coorg homestay booking for 30 Aug - 1 Sep 2024, in Downloads.', 'url': LAPTOP + '/files/docs/Coorg%20homestay%20-%20Wanderly.pdf'}),
    ('Users/Meera/Documents/Resume_Meera.pdf', 'LAP-DOC-07', 'document', '2024-08-14 11:20:00+05:30',
     "Meera's CV, updated August 2024: lead product designer at Anaia Design Studio since January 2022, previously product designer there from 2019; B.Des 2014-2018.",
     ['meera'], {'caption': 'Resume_Meera.pdf, in Documents. Updated three weeks before she disappeared.', 'url': LAPTOP + '/files/docs/Resume_Meera.pdf'}),
    ('Users/Meera/Documents/Aadhaar_Copy.pdf', 'LAP-DOC-08', 'document', '2023-04-11 00:00:00+05:30',
     'Scanned Aadhaar card: Meera Kapoor, born 12/03/1998, W/o Arjun Kapoor, Flat 402, Brigade Sanctuary, HSR Layout Sector 2, Bengaluru 560102.',
     ['meera', 'arjun'], {'caption': 'Aadhaar_Copy.pdf, in Documents. Her address and date of birth.', 'url': LAPTOP + '/files/docs/Aadhaar_Copy.pdf'}),
    ('Users/Meera/Documents/Passport.pdf', 'LAP-DOC-09', 'document', '2022-05-18 00:00:00+05:30',
     'Scan of her passport, P8472913, issued Bengaluru 15/05/2022: Meera Kapoor, born 12/03/1998 at Bengaluru; father Ravi Sharma, mother Lakshmi Sharma, spouse Arjun Kapoor.',
     ['meera', 'arjun', 'ravi_sharma'], {'caption': 'Passport.pdf, in Documents. Pages 2 and 3, scanned.', 'url': LAPTOP + '/files/docs/Passport.pdf'}),
    ('Users/Meera/Documents/Insurance.pdf', 'LAP-DOC-10', 'document', '2024-04-12 00:00:00+05:30',
     'Sanjeevani health policy SHI/BLR/2024/0448271, 12 April 2024 to 11 April 2025: family floater of Rs 5,00,000, proposer Arjun Kapoor, spouse Meera Kapoor, no pre-existing conditions declared.',
     ['meera', 'arjun'], {'caption': 'Insurance.pdf, in Documents. The health cover, in his name, both of them on it.', 'url': LAPTOP + '/files/docs/Insurance.pdf'}),
    ('Users/Meera/Documents/Marriage_Certificate.pdf', 'LAP-DOC-11', 'document', '2021-02-22 00:00:00+05:30',
     'Certificate of marriage JYN/MR/2021/00418: Arjun Kapoor and Meera Sharma, married 14 February 2021 at Jayanagar, registered 22 February 2021; witnesses Rahul Nair and Priya Menon.',
     ['meera', 'arjun', 'rahul', 'priya'], {'caption': 'Marriage_Certificate.pdf, in Documents. Rahul Nair signed as a witness.', 'url': LAPTOP + '/files/docs/Marriage_Certificate.pdf'}),
    ('Users/Meera/Documents/Important_Contacts.docx', 'LAP-DOC-12', 'document', '2024-06-30 19:40:00+05:30',
     "Her contacts list: Arjun, her mother, Priya, Rahul, Nikhil Rao (noted as Northwind, work), her manager, the vet, the society office, the insurers and the policy numbers.",
     ['meera', 'arjun', 'rahul', 'nikhil', 'priya'], {'caption': 'Important_Contacts.docx, in Documents.', 'body': None}),
]


def node_at(tree, path):
    node = tree['C:']
    for part in path.split('/'):
        node = node['data'][part]
    return node


def sql_str(s):
    return "'" + str(s).replace("'", "''") + "'"


def write_keeping_eol(path, text, original):
    eol = '\r\n' if '\r\n' in original else '\n'
    io.open(path, 'w', encoding='utf-8', newline=eol).write(text)


def main():
    raw = io.open(DIR_JSON, encoding='utf-8', newline='').read()
    tree = json.loads(raw)
    rows = []
    for path, eid, typ, ts, summary, involves, content in FILES:
        node = node_at(tree, path)
        node.setdefault('info', {})['evidence_id'] = eid
        content = dict(content)
        if 'body' in content and content['body'] is None:
            content['body'] = node['data']
        if node.get('type') == 'img':
            content['image_url'] = LAPTOP + node['data']
        rows.append("    (%s, 'desktop-shell', %s, %s,\n     %s,\n     ARRAY[%s], %s)" % (
            sql_str(eid), sql_str(typ), sql_str(ts), sql_str(summary),
            ', '.join(sql_str(i) for i in involves), sql_str(json.dumps(content, ensure_ascii=False))))
    write_keeping_eol(DIR_JSON, json.dumps(tree, indent=2, ensure_ascii=False) + '\n', raw)

    insert = ('INSERT INTO evidence_cache (evidence_id, service, type, timestamp, summary, involves, content) VALUES\n'
              + ',\n'.join(rows) + '\nON CONFLICT (evidence_id) DO UPDATE SET summary = EXCLUDED.summary, content = EXCLUDED.content, timestamp = EXCLUDED.timestamp;\n')

    raw_sql = io.open(INIT_SQL, encoding='utf-8', newline='').read()
    sql = raw_sql.replace('\r\n', '\n')
    block = '\n' + MARK + '\n' + insert
    if MARK in sql:
        # callable replacement: a string one would re-process the JSON bodies' \n escapes
        sql = re.sub(r'\n' + re.escape(MARK) + r'\n.*?;\n', lambda m: block, sql, count=1, flags=re.S)
    else:
        sql = sql.rstrip('\n') + '\n' + block
    write_keeping_eol(INIT_SQL, sql, raw_sql)
    print(insert)


if __name__ == '__main__':
    main()
