#!/usr/bin/env python
"""Every ordinary file on Meera's laptop is evidence the participant can
cite -- not only the ten affair photos. This stamps an evidence_id into each
node of desktop-shell's dir.json, appends the matching evidence_cache rows to
db/init.sql (fresh installs), and prints the same INSERT to apply to a live
database (so a running game keeps its discoveries):

    python scripts/seed_laptop_files.py | docker compose exec -T mercy-engine-db psql -U mercy -d mercy_engine
"""
import io
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
DIR_JSON = os.path.join(HERE, '..', '..', 'desktop-shell', 'src', 'reducers', 'dir.json')
INIT_SQL = os.path.join(HERE, '..', 'db', 'init.sql')
LAPTOP = 'http://localhost:3000'
MARK = '-- laptop-files (generated by scripts/seed_laptop_files.py)'

# path in dir.json -> record. Timestamps are the filename dates; summaries are
# what the picker searches, captions are what the evidence card shows.
FILES = [
    ('Users/Meera/Pictures/Camera Roll/IMG_20181007_073012.jpg', 'LAP-PHOTO-11', 'photo', '2018-10-07 07:30:00+05:30',
     'Breakfast with Dad at the Malleshwaram house, 7 October 2018 -- a week before he died. Dosas, the newspaper, his tea.',
     ['meera', 'ravi_sharma'], {'caption': 'Dad at breakfast, Malleshwaram, 7 October 2018. The last photo of him on this laptop.'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20240316_190455.jpg', 'LAP-PHOTO-12', 'photo', '2024-03-16 19:04:00+05:30',
     'College final-year project night, re-saved 16 March 2024: Nikhil, Rahul, Meera and Priya around one laptop.',
     ['meera', 'rahul', 'nikhil', 'priya'], {'caption': 'Final-year project night, college. Nikhil, Rahul standing, Meera, Priya.'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20240505_101233.jpg', 'LAP-PHOTO-13', 'photo', '2024-05-05 10:12:00+05:30',
     'Meera and Bruno in the garden, 5 May 2024.',
     ['meera'], {'caption': 'Meera and Bruno in the garden, 5 May 2024.'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20240505_101410.jpg', 'LAP-PHOTO-14', 'photo', '2024-05-05 10:14:00+05:30',
     "Bruno's fourth birthday, 5 May 2024 -- balloons, a chicken cake, the banner.",
     ['meera'], {'caption': "Bruno's fourth birthday, 5 May 2024. The chicken cake did not survive the afternoon."}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20240622_123301.jpg', 'LAP-PHOTO-15', 'photo', '2024-06-22 12:33:00+05:30',
     'Sunday brunch at the cafe, 22 June 2024. Alone at the table; avocado toast and a flat white.',
     ['meera'], {'caption': 'Sunday brunch, 22 June 2024. Alone at the table.'}),
    ('Users/Meera/Pictures/Camera Roll/IMG_20240817_203344.jpg', 'LAP-PHOTO-16', 'photo', '2024-08-17 20:33:00+05:30',
     "Dinner with Arjun, 17 August 2024 -- Dad's birthday. Candles; the chalkboard reads 'same people, brighter nights'.",
     ['meera', 'arjun'], {'caption': "Dinner with Arjun on Dad's birthday, 17 August 2024."}),
    ('Users/Meera/Desktop/todo.txt', 'LAP-DOC-01', 'document', '2024-08-28 09:00:00+05:30',
     'todo.txt on the desktop: water bill, call Priya re Sunday, Bruno vet Saturday, return the dish, ask Arjun about Coorg dates, cancel the gym before the 30th.',
     ['meera'], {'caption': 'todo.txt, on the desktop.', 'body': None}),
    ('Users/Meera/Documents/notes.txt', 'LAP-DOC-02', 'document', '2024-08-20 21:00:00+05:30',
     "notes.txt in Documents: recipes to try (bisi bele bath, Dad's proportions from the diary), books, and a birthday gift idea for Arjun.",
     ['meera'], {'caption': 'notes.txt, in Documents.', 'body': None}),
    ('Users/Meera/Documents/Insurance/LIC_policy_2019.pdf', 'LAP-DOC-03', 'document', '2019-03-19 00:00:00+05:30',
     'LIC Jeevan Anand policy schedule, commenced 19 March 2019: life assured Meera Sharma, born 12 March 1998, sum assured Rs 10 lakh, nominee Lakshmi Sharma (mother).',
     ['meera'], {'caption': 'LIC policy schedule, 2019. Nominee: her mother.', 'url': LAPTOP + '/files/docs/LIC_policy_2019.pdf'}),
    ('Users/Meera/Documents/Office/Q2_review_notes.txt', 'LAP-DOC-04', 'document', '2024-07-08 18:30:00+05:30',
     'Q2 review talking points from work: accounts, renewals, the onboarding flow.',
     ['meera'], {'caption': 'Q2_review_notes.txt, in Documents/Office.', 'body': None}),
    ('Users/Meera/Downloads/PulseFit-export-Aug.csv', 'LAP-DOC-05', 'document', '2024-08-31 00:00:00+05:30',
     "PulseFit export for August 2024: daily steps, resting heart rate and sleep hours from Meera's band.",
     ['meera'], {'caption': 'PulseFit-export-Aug.csv, in Downloads.', 'body': None}),
    ('Users/Meera/Downloads/Coorg homestay - Wanderly.pdf', 'LAP-DOC-06', 'document', '2024-08-12 00:00:00+05:30',
     'Wanderly booking confirmation WDL-8H3K2Q: Misty Ridge Homestay, Madikeri, Coorg, 30 August to 1 September 2024, 2 adults, pet-friendly. Free cancellation until 23 August.',
     ['meera', 'arjun'], {'caption': 'Coorg homestay booking for 30 Aug - 1 Sep 2024, in Downloads.', 'url': LAPTOP + '/files/docs/Coorg%20homestay%20-%20Wanderly.pdf'}),
]


def node_at(tree, path):
    node = tree['C:']
    for part in path.split('/'):
        node = node['data'][part]
    return node


def sql_str(s):
    return "'" + str(s).replace("'", "''") + "'"


def write_keeping_eol(path, text, original):
    eol = '\r\n' if '\r\n' in original else '\n'
    io.open(path, 'w', encoding='utf-8', newline=eol).write(text)


def main():
    raw = io.open(DIR_JSON, encoding='utf-8', newline='').read()
    tree = json.loads(raw)
    rows = []
    for path, eid, typ, ts, summary, involves, content in FILES:
        node = node_at(tree, path)
        node.setdefault('info', {})['evidence_id'] = eid
        content = dict(content)
        if 'body' in content and content['body'] is None:
            content['body'] = node['data']
        if node.get('type') == 'img':
            content['image_url'] = LAPTOP + node['data']
        rows.append("    (%s, 'desktop-shell', %s, %s,\n     %s,\n     ARRAY[%s], %s)" % (
            sql_str(eid), sql_str(typ), sql_str(ts), sql_str(summary),
            ', '.join(sql_str(i) for i in involves), sql_str(json.dumps(content, ensure_ascii=False))))
    write_keeping_eol(DIR_JSON, json.dumps(tree, indent=2, ensure_ascii=False) + '\n', raw)

    insert = ('INSERT INTO evidence_cache (evidence_id, service, type, timestamp, summary, involves, content) VALUES\n'
              + ',\n'.join(rows) + '\nON CONFLICT (evidence_id) DO UPDATE SET summary = EXCLUDED.summary, content = EXCLUDED.content, timestamp = EXCLUDED.timestamp;\n')

    raw_sql = io.open(INIT_SQL, encoding='utf-8', newline='').read()
    sql = raw_sql.replace('\r\n', '\n')
    block = '\n' + MARK + '\n' + insert
    if MARK in sql:
        # callable replacement: a string one would re-process the JSON bodies' \n escapes
        sql = re.sub(r'\n' + re.escape(MARK) + r'\n.*?;\n', lambda m: block, sql, count=1, flags=re.S)
    else:
        sql = sql.rstrip('\n') + '\n' + block
    write_keeping_eol(INIT_SQL, sql, raw_sql)
    print(insert)


if __name__ == '__main__':
    main()
